name: nojima-watcher

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分ごと
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i playwright@1

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run monitor
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: node monitor_nojima.js

      - name: Commit state
        if: success()
        run: |
          git config user.name "nojima-watcher"
          git config user.email "bot@example.com"
          git add nojima_seen.json || true
          git commit -m "update seen" || true
          git push || true
